// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaalGPhWlii-68QnWbliKlXrmXwuhjpqE',
    appId: '1:405659381663:android:d3cdac3abd38d90f0b57aa',
    messagingSenderId: '405659381663',
    projectId: 'ekonnect-272da',
    storageBucket: 'ekonnect-272da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiHf0riBnuCoIgg-WNG3WKZmbFFflCb6M',
    appId: '1:405659381663:ios:7a05ee4905eb35cf0b57aa',
    messagingSenderId: '405659381663',
    projectId: 'ekonnect-272da',
    storageBucket: 'ekonnect-272da.firebasestorage.app',
    androidClientId: '405659381663-h0pd3jbb27jkivh8n8qjen2ra5ebos47.apps.googleusercontent.com',
    iosClientId: '405659381663-d12ub0vs9rbal6jkqiss53kf3nvghl1u.apps.googleusercontent.com',
    iosBundleId: 'com.konnect.erestrorider',
  );
}
