// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaalGPhWlii-68QnWbliKlXrmXwuhjpqE',
    appId: '1:405659381663:android:337afcebaf209ede0b57aa',
    messagingSenderId: '405659381663',
    projectId: 'ekonnect-272da',
    storageBucket: 'ekonnect-272da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiHf0riBnuCoIgg-WNG3WKZmbFFflCb6M',
    appId: '1:405659381663:ios:3dac14b5183c03af0b57aa',
    messagingSenderId: '405659381663',
    projectId: 'ekonnect-272da',
    storageBucket: 'ekonnect-272da.firebasestorage.app',
    iosBundleId: 'com.konnect.erestro',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN1VWb6rbs07rDJFINIQKN6VT296yednk',
    appId: '1:405659381663:web:33fee3be96b110dd0b57aa',
    messagingSenderId: '405659381663',
    projectId: 'ekonnect-272da',
    authDomain: 'ekonnect-272da.firebaseapp.com',
    storageBucket: 'ekonnect-272da.firebasestorage.app',
    measurementId: 'G-W1K9ZJZTM9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiHf0riBnuCoIgg-WNG3WKZmbFFflCb6M',
    appId: '1:405659381663:ios:9bf55f68648ad4e90b57aa',
    messagingSenderId: '405659381663',
    projectId: 'ekonnect-272da',
    storageBucket: 'ekonnect-272da.firebasestorage.app',
    iosBundleId: 'com.wrteam.erestro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN1VWb6rbs07rDJFINIQKN6VT296yednk',
    appId: '1:405659381663:web:3b8b15215a65c6e00b57aa',
    messagingSenderId: '405659381663',
    projectId: 'ekonnect-272da',
    authDomain: 'ekonnect-272da.firebaseapp.com',
    storageBucket: 'ekonnect-272da.firebasestorage.app',
    measurementId: 'G-YVC2JZBF19',
  );

}